services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mysqlDB
      - MYSQL_ROOT_PASSWORD=mysqlPW
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    command: --max_connections=500 --default-authentication-plugin=mysql_native_password
